from app.schemas.auth import (
    Country,
    UserRegistration,
    UserLogin,
    UserResponse,
    AuthenticationResponse,
    TokenResponse,
    LoginResponse,
    ForgotPinRequest,
    ForgotPinResponse,
    ChangePinRequest,
    ChangePinResponse,
    VerifyEmailRequest,
    ResendVerificationRequest,
    SetNewPinRequest,
    UserInformation,
    UserUpdateRequest,
    UpdateUserInformation,
    UserDeleteAccountResponse,
    AdminUserListItem,
    AdminUserListResponse,
    AdminUserToggleRequest,
    AdminUserToggleResponse,
    AdminCountryToggleRequest,
    AdminCountryToggleResponse,
    AdminCountryListItem,
    AdminCountryListAllResponse,
)
from app.schemas.feed import (
    FeedTypeBase,
    FeedTypeCreate,
    FeedTypeUpdate,
    FeedTypeResponse,
    FeedCategoryBase,
    FeedCategoryCreate,
    FeedCategoryUpdate,
    FeedCategoryResponse,
    FeedClassificationStructure,
    FeedClassificationStructureResponse,
    FeedDetailsResponse,
    FeedDescriptionResponse,
    AdminFeedTypeRequest,
    AdminFeedTypeResponse,
    AdminFeedCategoryRequest,
    AdminFeedCategoryResponse,
    AdminFeedRequest,
    AdminFeedResponse,
    AdminFeedListResponse,
    AdminBulkUploadResponse,
    AdminExportResponse,
    AdminBulkLogResponse,
)
from app.schemas.animal import (
    AnimalCharacteristics,
    CattleInfo,
    FeedWithPrice,
    BaseThresholds,
    DietRecommendationRequest,
    AnimalCharacteristicItem,
    AnimalCharacteristicsData,
    SelectedFeedItem,
    CategoryBreakdownItem,
    DietSummaryDetailed,
    DietRecommendationResponse,
    FeedEvaluationItem,
    DietEvaluationRequest,
    MilkProductionAnalysis,
    IntakeEvaluation,
    CostAnalysis,
    MethaneAnalysis,
    NutrientBalance,
    FeedBreakdownItem,
    DietEvaluationSummary,
    DietEvaluationResponse,
    FeedAnalyticsBase,
    FeedAnalyticsCreate,
    FeedAnalyticsUpdate,
    FeedAnalyticsResponse,
)
from app.schemas.report import (
    PDFReportMetadata,
    PDFReportList,
    PDFReportResponse,
    ReportBase,
    ReportCreate,
    ReportResponse,
    SaveReportRequest,
    SaveReportResponse,
    UserReportItem,
    GetUserReportsResponse,
    FetchAllSimulationsRequest,
    SimulationListItem,
    FetchAllSimulationsResponse,
    FetchSimulationDetailsRequest,
    SimulationFeedDetail,
    FetchSimulationDetailsResponse,
    AdminGetAllReportsRequest,
    AdminReportItem,
    AdminGetAllReportsResponse,
    FeedbackSubmitRequest,
    UserFeedbackResponse,
    AdminFeedbackResponse,
    FeedbackListResponse,
    AdminFeedbackListResponse,
    FeedbackStatsResponse,
)

__all__ = [
    # auth
    "Country", "UserRegistration", "UserLogin", "UserResponse", "AuthenticationResponse",
    "TokenResponse", "LoginResponse",
    "ForgotPinRequest", "ForgotPinResponse", "ChangePinRequest", "ChangePinResponse",
    "VerifyEmailRequest", "ResendVerificationRequest", "SetNewPinRequest",
    "UserInformation", "UserUpdateRequest", "UpdateUserInformation",
    "UserDeleteAccountResponse",
    "AdminUserListItem", "AdminUserListResponse", "AdminUserToggleRequest", "AdminUserToggleResponse",
    "AdminCountryToggleRequest", "AdminCountryToggleResponse",
    "AdminCountryListItem", "AdminCountryListAllResponse",
    # feed
    "FeedTypeBase", "FeedTypeCreate", "FeedTypeUpdate", "FeedTypeResponse",
    "FeedCategoryBase", "FeedCategoryCreate", "FeedCategoryUpdate", "FeedCategoryResponse",
    "FeedClassificationStructure", "FeedClassificationStructureResponse",
    "FeedDetailsResponse", "FeedDescriptionResponse",
    "AdminFeedTypeRequest", "AdminFeedTypeResponse",
    "AdminFeedCategoryRequest", "AdminFeedCategoryResponse",
    "AdminFeedRequest", "AdminFeedResponse", "AdminFeedListResponse",
    "AdminBulkUploadResponse", "AdminExportResponse", "AdminBulkLogResponse",
    # animal
    "AnimalCharacteristics", "CattleInfo", "FeedWithPrice", "BaseThresholds",
    "DietRecommendationRequest", "AnimalCharacteristicItem", "AnimalCharacteristicsData",
    "SelectedFeedItem", "CategoryBreakdownItem", "DietSummaryDetailed", "DietRecommendationResponse",
    "FeedEvaluationItem", "DietEvaluationRequest",
    "MilkProductionAnalysis", "IntakeEvaluation", "CostAnalysis", "MethaneAnalysis",
    "NutrientBalance", "FeedBreakdownItem", "DietEvaluationSummary", "DietEvaluationResponse",
    "FeedAnalyticsBase", "FeedAnalyticsCreate", "FeedAnalyticsUpdate", "FeedAnalyticsResponse",
    # report
    "PDFReportMetadata", "PDFReportList", "PDFReportResponse",
    "ReportBase", "ReportCreate", "ReportResponse",
    "SaveReportRequest", "SaveReportResponse",
    "UserReportItem", "GetUserReportsResponse",
    "FetchAllSimulationsRequest", "SimulationListItem", "FetchAllSimulationsResponse",
    "FetchSimulationDetailsRequest", "SimulationFeedDetail", "FetchSimulationDetailsResponse",
    "AdminGetAllReportsRequest", "AdminReportItem", "AdminGetAllReportsResponse",
    "FeedbackSubmitRequest", "UserFeedbackResponse", "AdminFeedbackResponse",
    "FeedbackListResponse", "AdminFeedbackListResponse", "FeedbackStatsResponse",
]
